name: deepl-dialog

on:
  push:
  pull_request:

jobs:
  build:
    name: deepl-dialog
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - name: Install dependencies
        run: shards install --without-development --release
      - name: Build executable
        run: crystal build examples/deepl-dialog.cr --release
      - uses: actions/upload-artifact@v3
        with:
          name: deepl-dialog
          path: deepl-dialog.exe
